version: "2"

networks:
  as_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

services:
  coord:
    image:  circleci/python:3.6.1
    container_name: coord
    working_dir: /home/circleci/repo
    environment:
      PYTHONPATH: /tmp/scion/python
    user: root
    networks:
      as_net:
        ipv4_address: 172.31.0.10
    ports:
      - "8432:8000"
    # waits for setup script to be loaded
    entrypoint: /bin/bash
    command: -c "./scionlab/.circleci/setup/coord.sh"

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      as_net:
        ipv4_address: 172.31.0.11
    restart: always

  coreAS1301:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
    image: scionhost:tmp
    container_name: coreAS1301
    depends_on:
      - zookeeper
      - coord
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${coreAS1301IP}
    user: scion
    environment:
      # host id/secret from fixture
      CUSER: 098625df419a48279761954bb7b4ce78
      CSECRET: 10cc1584deea4a10b9210a4c03c2d872
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/reloadASConfig.sh; ${SC}/reloadASConfig.sh; cat;"

  infraAS1303:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
        - JACKAL=${JACKAL}
        - JACKAL_ID="server1"
    image: scionhost:tmp
    container_name: infraAS1303
    depends_on:
      - zookeeper
      - coreAS1301
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${infraAS1303IP}
    user: scion
    environment:
      CUSER: f5422107f7354c55b9f54a4befe0f58d
      CSECRET: a2532f97fe144a88944e2860e525f220
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/reloadASConfig.sh; ${SC}/reloadASConfig.sh; cat;"

  infraAS1305:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
        - JACKAL=${JACKAL}
        - JACKAL_ID="server2"
    image: scionhost:tmp
    container_name: infraAS1305
    depends_on:
      - zookeeper
      - coreAS1301
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${infraAS1305IP}
    user: scion
    environment:
      CUSER: 4a715f91a023481fb21e61669777238f
      CSECRET: ab4c5aa179be4a37ba7db180517ea6f5
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/reloadASConfig.sh; ${SC}/reloadASConfig.sh; cat;"
