version: "2"

networks:
  as_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

services:
  coreAS1301:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
        - JACKAL_DIR=${JACKAL_DIR}
    image: scionhost:tmp
    container_name: coreAS1301
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${coreAS1301IP}
    user: scion
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/loadASConfig.sh; ${SC}/loadASConfig.sh; cat;"

  infraAS1303:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
        - JACKAL_DIR=${JACKAL_DIR}
    image: scionhost:tmp
    container_name: infraAS1303
    depends_on:
      - coreAS1301
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${infraAS1303IP}
    user: scion
    environment:
      JACKAL_ID: server1
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/loadASConfig.sh; ${SC}/loadASConfig.sh; cat;"

  infraAS1305:
    build:
      context: .
      dockerfile: Dockerfile-scionHost
      args:
        - SCION_SRC=${SCION_SRC}
        - SC=${SC}
        - JACKAL_DIR=${JACKAL_DIR}
    image: scionhost:tmp
    container_name: infraAS1305
    depends_on:
      - coreAS1301
    working_dir: /home/scion/go/src/github.com/scionproto/scion
    networks:
      as_net:
        ipv4_address: ${infraAS1305IP}
    user: scion
    environment:
      JACKAL_ID: server2
    tty: true
    entrypoint: /bin/bash
    command: -c "ls ${SC}/loadASConfig.sh; ${SC}/loadASConfig.sh; cat;"

  profanity1:
    image: ubuntu:18.04
    container_name: profanity1
    working_dir: /home
    networks:
      as_net:
        ipv4_address: 172.31.0.12
    environment:
      CLIENT_ID: client1
    tty: true
    entrypoint: /bin/bash

  profanity2:
    image: ubuntu:18.04
    container_name: profanity2
    working_dir: /home
    networks:
      as_net:
        ipv4_address: 172.31.0.13
    environment:
      CLIENT_ID: client2
    tty: true
    entrypoint: /bin/bash
